#!/bin/bash
# config/defaults.sh
# Default values for the charon pipeline call.

DEFAULT_DATASET=""
DEFAULT_DATASET_DIR=""
DEFAULT_TRACER=""
DEFAULT_SUFFIX=""
DEFAULT_WORKDIR=""
DEFAULT_OUTDIR=""
DEFAULT_FS_LICENSE=""
DEFAULT_PETPREP_SIF=""
DEFAULT_FASTSURFER_SIF=""
DEFAULT_MRI_PET_DAYDIFF=365
DEFAULT_SCAN_SELECTION="earliest"
DEFAULT_REUSE=false
DEFAULT_PILOT=false
DEFAULT_NO_SESSION=false
DEFAULT_SES_FORMAT="date"
DEFAULT_IMAGE_PAIRS=""
DEFAULT_TEMPLATEFLOW_HOME=""
DEFAULT_RUN_CONFIG=""